name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run File and collect logs
      id: run
      run:  |
        echo Running File...
        status=$(python script.py > log.txt 2>&1; echo $?)
        cat log.txt
        echo ::set-output name=status::$status
    - name: Commit log
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add -A
        git checkout master
        git diff-index --quiet HEAD || git commit -am "deploy workflow logs"
        git push

    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Run tests
      run: mvn test
      id: tests

    - name: "telegram-success"
      if: success()
      uses: "appleboy/telegram-action@master"
      with:
        to: ${{ secrets.USER_ID }}
        token: ${{ secrets.BOT_TOKEN }}
        args: Новая версия успешно загружена в репозиторий

    - name: "telegram-failure"
      if: failure()
      uses: "appleboy/telegram-action@master"
      with:
        to: ${{ secrets.USER_ID }}
        token: ${{ secrets.BOT_TOKEN }}
        args: Тесты не прошли ${{steps.run.outputs.status}}
